apiVersion: v1
kind: ConfigMap
data:
  PORT_CONNECTION: 30001
  PORT_PERSON: 30002
  ENDPOINT_CONNECTION: 'http://localhost:30001/api/persons/${personId}/connection?start_date=2020-01-01&end_date=2020-12-30&distance=5'
  ENDPOINT_PERSON: 'http://localhost:30001/api/persons'
metadata:
  name: endpoint-env
