apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-service
  name: udaconnect-location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-service
  template:
    metadata:
      labels:
        service: udaconnect-location-service
    spec:
      containers:
      - image: pausch94/nd064-udaconnect-location-service:latest
        name: udaconnect-location-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_LOCATION_PORT
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: GRPC_LOCATION_PORT 
        - name: KAFKA_LOCATION_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_LOCATION_TOPIC
      restartPolicy: Always
