apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-api
  name: udaconnect-connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-api
  template:
    metadata:
      labels:
        service: udaconnect-connection-api
    spec:
      containers:
      - image: pausch94/nd064-udaconnect-connection-api:latest
        name: udaconnect-connection-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_CONNECTION_PORT
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: GRPC_CONNECTION_PORT
        - name: GRPC_CONNECTION_HOST
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: GRPC_CONNECTION_HOST
      restartPolicy: Always
