apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-api
  name: udaconnect-person-api
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
    nodePort: 31100
  selector:
    service: udaconnect-person-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-api
  name: udaconnect-person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-api
  template:
    metadata:
      labels:
        service: udaconnect-person-api
    spec:
      containers:
      - image: pausch94/nd064-udaconnect-person-api:latest
        name: udaconnect-person-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_PERSON_PORT
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: GRPC_PERSON_PORT
        - name: GRPC_PERSON_HOST
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: GRPC_PERSON_HOST
        - name: KAFKA_PERSON_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_PERSON_TOPIC
      restartPolicy: Always
